## Project Description: Next Word Prediction Using LSTM
#### Project Overview:

This project aims to develop a deep learning model for predicting the next word in a given sequence of words. The model is built using Long Short-Term Memory (LSTM) networks, which are well-suited for sequence prediction tasks. The project includes the following steps:

1- Data Collection: We use the text of Shakespeare's "Hamlet" as our dataset. This rich, complex text provides a good challenge for our model.

2- Data Preprocessing: The text data is tokenized, converted into sequences, and padded to ensure uniform input lengths. The sequences are then split into training and testing sets.

3- Model Building: An LSTM model is constructed with an embedding layer, two LSTM layers, and a dense output layer with a softmax activation function to predict the probability of the next word.

4- Model Training: The model is trained using the prepared sequences, with early stopping implemented to prevent overfitting. Early stopping monitors the validation loss and stops training when the loss stops improving.

5- Model Evaluation: The model is evaluated using a set of example sentences to test its ability to predict the next word accurately.

6- Deployment: A Streamlit web application is developed to allow users to input a sequence of words and get the predicted next word in real-time.

In [2]:
## Data Collection
import nltk
nltk.download('gutenberg')
from nltk.corpus import gutenberg
import  pandas as pd

## load the dataset
data=gutenberg.raw('shakespeare-hamlet.txt')
## save to a file
with open('hamlet.txt','w') as file:
    file.write(data)

[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\ashis\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\gutenberg.zip.


In [27]:
## Data Preprocessing

import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

##laod the dataset
with open('hamlet.txt','r') as file:
    text=file.read().lower()

## Tokenize the text-creating indexes for words
tokenizer = Tokenizer(num_words=5000, oov_token="<OOV>")
tokenizer.fit_on_texts([text])
total_words = min(5000, len(tokenizer.word_index) + 1)
total_words



4819

In [30]:
tokenizer.word_index

{'<OOV>': 1,
 'the': 2,
 'and': 3,
 'to': 4,
 'of': 5,
 'i': 6,
 'you': 7,
 'a': 8,
 'my': 9,
 'it': 10,
 'in': 11,
 'that': 12,
 'ham': 13,
 'is': 14,
 'not': 15,
 'his': 16,
 'this': 17,
 'with': 18,
 'your': 19,
 'but': 20,
 'for': 21,
 'me': 22,
 'lord': 23,
 'as': 24,
 'what': 25,
 'he': 26,
 'be': 27,
 'so': 28,
 'him': 29,
 'haue': 30,
 'king': 31,
 'will': 32,
 'no': 33,
 'our': 34,
 'we': 35,
 'on': 36,
 'are': 37,
 'if': 38,
 'all': 39,
 'then': 40,
 'shall': 41,
 'by': 42,
 'thou': 43,
 'come': 44,
 'or': 45,
 'hamlet': 46,
 'good': 47,
 'do': 48,
 'hor': 49,
 'her': 50,
 'let': 51,
 'now': 52,
 'thy': 53,
 'how': 54,
 'more': 55,
 'they': 56,
 'from': 57,
 'enter': 58,
 'at': 59,
 'was': 60,
 'oh': 61,
 'like': 62,
 'most': 63,
 'there': 64,
 'well': 65,
 'know': 66,
 'selfe': 67,
 'would': 68,
 'them': 69,
 'loue': 70,
 'may': 71,
 "'tis": 72,
 'vs': 73,
 'sir': 74,
 'qu': 75,
 'which': 76,
 'did': 77,
 'why': 78,
 'laer': 79,
 'giue': 80,
 'thee': 81,
 'ile': 82,
 'must':

In [47]:
## create inoput sequences
## create input sequences
input_sequences = []

sequence_length = 20

token_list = tokenizer.texts_to_sequences([text])[0]

for i in range(sequence_length, len(token_list)):
    n_gram_sequence = token_list[i-sequence_length:i+1]
    input_sequences.append(n_gram_sequence)

        

In [48]:
max_sequence_len = max([len(x) for x in input_sequences])
print(max_sequence_len)


21


In [49]:
input_sequences

[[2,
  688,
  5,
  46,
  42,
  1887,
  1888,
  1889,
  1181,
  1890,
  1891,
  1892,
  58,
  408,
  3,
  1182,
  178,
  1893,
  408,
  1183,
  64],
 [688,
  5,
  46,
  42,
  1887,
  1888,
  1889,
  1181,
  1890,
  1891,
  1892,
  58,
  408,
  3,
  1182,
  178,
  1893,
  408,
  1183,
  64,
  409],
 [5,
  46,
  42,
  1887,
  1888,
  1889,
  1181,
  1890,
  1891,
  1892,
  58,
  408,
  3,
  1182,
  178,
  1893,
  408,
  1183,
  64,
  409,
  163],
 [46,
  42,
  1887,
  1888,
  1889,
  1181,
  1890,
  1891,
  1892,
  58,
  408,
  3,
  1182,
  178,
  1893,
  408,
  1183,
  64,
  409,
  163,
  378],
 [42,
  1887,
  1888,
  1889,
  1181,
  1890,
  1891,
  1892,
  58,
  408,
  3,
  1182,
  178,
  1893,
  408,
  1183,
  64,
  409,
  163,
  378,
  22],
 [1887,
  1888,
  1889,
  1181,
  1890,
  1891,
  1892,
  58,
  408,
  3,
  1182,
  178,
  1893,
  408,
  1183,
  64,
  409,
  163,
  378,
  22,
  248],
 [1888,
  1889,
  1181,
  1890,
  1891,
  1892,
  58,
  408,
  3,
  1182,
  178,
  1893,
  408,

In [50]:
## Pad Sequences
max_sequence_len=max([len(x) for x in input_sequences])
max_sequence_len

21

In [51]:
input_sequences=np.array(pad_sequences(input_sequences,maxlen=max_sequence_len,padding='pre'))
input_sequences

array([[   2,  688,    5, ...,  408, 1183,   64],
       [ 688,    5,   46, ..., 1183,   64,  409],
       [   5,   46,   42, ...,   64,  409,  163],
       ...,
       [   2, 4814, 1886, ...,    5,   46, 1048],
       [4814, 1886,  176, ...,   46, 1048,    5],
       [1886,  176, 4815, ..., 1048,    5,  194]],
      shape=(29678, 21), dtype=int32)

In [52]:
##create predicitors and label
import tensorflow as tf
x,y=input_sequences[:,:-1],input_sequences[:,-1]

In [53]:
x

array([[   2,  688,    5, ..., 1893,  408, 1183],
       [ 688,    5,   46, ...,  408, 1183,   64],
       [   5,   46,   42, ..., 1183,   64,  409],
       ...,
       [   2, 4814, 1886, ...,  688,    5,   46],
       [4814, 1886,  176, ...,    5,   46, 1048],
       [1886,  176, 4815, ...,   46, 1048,    5]],
      shape=(29678, 20), dtype=int32)

In [54]:
y

array([  64,  409,  163, ..., 1048,    5,  194],
      shape=(29678,), dtype=int32)

In [55]:
y=tf.keras.utils.to_categorical(y,num_classes=total_words)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(29678, 4819))

In [56]:
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [57]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.optimizers import Adam


model = Sequential()

# 🔑 ADD THIS LINE (this is the fix)
model.add(Embedding(
    input_dim=total_words,
    output_dim=128,
    input_length=max_sequence_len - 1
))

# keep your LSTM exactly the same
model.add(LSTM(150))
model.add(Dropout(0.2))

# output layer unchanged
model.add(Dense(total_words, activation='softmax'))

model.compile(
    loss='categorical_crossentropy',
   optimizer=Adam(learning_rate=0.001),
    metrics=['accuracy']
)
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_7 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [59]:
#train the model
from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=15,
    restore_best_weights=True
)

history = model.fit(
    x, y,
    epochs=120,
    validation_split=0.2,
    callbacks=[early_stop],
    verbose=1
)


Epoch 1/120
742/742 ━━━━━━━━━━━━━━━━━━━━ 19s 26ms/step - accuracy: 0.0400 - loss: 6.3359 - val_accuracy: 0.0401 - val_loss: 7.3182
Epoch 2/120
742/742 ━━━━━━━━━━━━━━━━━━━━ 19s 25ms/step - accuracy: 0.0494 - loss: 6.1623 - val_accuracy: 0.0487 - val_loss: 7.4184
Epoch 3/120
742/742 ━━━━━━━━━━━━━━━━━━━━ 19s 25ms/step - accuracy: 0.0606 - loss: 5.9829 - val_accuracy: 0.0505 - val_loss: 7.4811
Epoch 4/120
742/742 ━━━━━━━━━━━━━━━━━━━━ 18s 25ms/step - accuracy: 0.0735 - loss: 5.7897 - val_accuracy: 0.0553 - val_loss: 7.5077
Epoch 5/120
742/742 ━━━━━━━━━━━━━━━━━━━━ 18s 25ms/step - accuracy: 0.0865 - loss: 5.5510 - val_accuracy: 0.0677 - val_loss: 7.6567
Epoch 6/120
742/742 ━━━━━━━━━━━━━━━━━━━━ 18s 24ms/step - accuracy: 0.0962 - loss: 5.2961 - val_accuracy: 0.0654 - val_loss: 7.8117
Epoch 7/120
742/742 ━━━━━━━━━━━━━━━━━━━━ 18s 24ms/step - accuracy: 0.1097 - loss: 5.0342 - val_accuracy: 0.0640 - val_loss: 7.9355
Epoch 8/120
742/742 ━━━━━━━━━━━━━━━━━━━━ 18s 24ms/step - accuracy: 0.1296 - loss: 4

In [60]:
# Function to predict the next word
def predict_next_word(model, tokenizer, text, max_sequence_len):
    token_list = tokenizer.texts_to_sequences([text])[0]
    if len(token_list) >= max_sequence_len:
        token_list = token_list[-(max_sequence_len-1):]  # Ensure the sequence length matches max_sequence_len-1
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = model.predict(token_list, verbose=0)
    predicted_word_index = np.argmax(predicted, axis=1)
    for word, index in tokenizer.word_index.items():
        if index == predicted_word_index:
            return word
    return None

In [61]:
input_text="To be or not to be"
print(f"Input text:{input_text}")
max_sequence_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next Word PRediction:{next_word}")

Input text:To be or not to be
Next Word PRediction:the


In [64]:
## Save the model
model.save("next_word_lstm.keras")
## Save the tokenizer
import pickle
with open('tokenizer.pickle','wb') as handle:
    pickle.dump(tokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)

In [65]:
input_text="  Barn. Last night of all,When yond same"
print(f"Input text:{input_text}")
max_sequence_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next Word PRediction:{next_word}")

Input text:  Barn. Last night of all,When yond same
Next Word PRediction:the
